
version: '2'
services:
   redis:
      image: redis
      container_name: redis_bk
      restart: always
      ports:
        - 10109:6379
      volumes:
        - ./conf/redis.conf:/etc/redis/redis.conf
        - ./data:/data
      command: redis-server /etc/redis/redis.conf --appendonly yes
